s = input("Pergunte algo: ")
print("o tipo primitivo desse valor é", type(s))
print("só tem espaços?", s.isspace() )
print("é um numero?", s.isnumeric())
print("é alfabetico?", s.isalpha())
print("é alfanumerico?", s.isalnum())
print("está em maiúsculas?", s.isupper())
print("está em maiúsculas?", s.islower())
print("está capitalizada?", s.istitle())
